### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by bymihaj** [mps256/vicuna.ps1#2]
On PC PowerShell script placed main.exe into folder C:\VICUNA\llama-master-master-cc9cee8--x64\main.exe but vicuna.bat is expected at C:\VICUNA\main.exe

**Comment by mps256** [comment]
On my way!

**Comment by Bidetsan** [comment]
That's what we are saying

**Comment by Bidetsan** [comment]
quick fix <--
VICUNA folder have to be filled by file (main.exe, perplexity.exe etc.) in llama-master-master-62xxx12--x64

**Comment by mps256** [comment]
I'm implementing some hash stuff also
